language: php

git:
  depth: 2

matrix:
  include:
    - php: hhvm
    - php: 8.0
    - php: 7.4

  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test
